version: '3'
services:
  postgres-db:
    container_name: cpts-451-database
    image: nkarl/cpts-451-postgres
    environment:
      #POSTGRES_DB: business_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: none
    ports:
      - 5032:5032
    volumes:
      - ./database:/database
    working_dir: '/database'

volumes:
  postgres-db:
    name: database
