version: '3'
services:
  postgres-db:
    container_name: cpts-451-database
    image: nkarl/cpts-451-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: yelpdb
    ports:
      - "5432:5432"
    volumes:
      - ./database:/database
    working_dir: '/database'

volumes:
  postgres-db:
    name: database
